# docker-compose.yml
version: '3.1'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
     - POSTGRES_HOST="${POSTGRES_HOST}"
     - POSTGRES_USER="${POSTGRES_USER}"
     - POSTGRES_PASSWORD="${POSTGRES_PASSWORD}"
     - POSTGRES_DB="${POSTGRES_DB}"
     - POSTGRES_CONTAINER_PORT="${POSTGRES_CONTAINER_PORT}"
     - POSTGRES_HOST_PORT="${POSTGRES_HOST_PORT}"
    ports: 
      - "${POSTGRES_HOST_PORT}:${POSTGRES_CONTAINER_PORT}"
    volumes:
      - ./database:/var/lib/postgresql/data